name: Ladder Engine

on:
#  schedule:
#    - cron: '0,30 * * * *' # Run every 30 minutes
  workflow_dispatch: # Allow manual run

permissions:
  contents: write

jobs:
  engine:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Referee
        env:
          WZ_EMAIL: ${{ secrets.WZ_EMAIL }}
          WZ_API_TOKEN: ${{ secrets.WZ_API_TOKEN }}
        run: node scripts/referee.js

      - name: Run Matchmaker
        env:
          WZ_EMAIL: ${{ secrets.WZ_EMAIL }}
          WZ_API_TOKEN: ${{ secrets.WZ_API_TOKEN }}
        run: node scripts/matchmaker.js

      - name: Commit State Changes
        run: |
          git config --global user.name "Norman (Bot)"
          git config --global user.email "norman-bot@users.noreply.github.com"
          git add data/
          git commit -m "Engine: Update state" || echo "No changes to commit"
          git push
